//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuenosAires.BodegaBA.WsProductoAnwoReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsProductoAnwoReference.IWsProductoAwno")]
    public interface IWsProductoAwno {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsProductoAwno/LeerTodos", ReplyAction="http://tempuri.org/IWsProductoAwno/LeerTodosResponse")]
        BuenosAires.Model.Respuesta LeerTodos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsProductoAwno/LeerTodos", ReplyAction="http://tempuri.org/IWsProductoAwno/LeerTodosResponse")]
        System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> LeerTodosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsProductoAwno/Reservar", ReplyAction="http://tempuri.org/IWsProductoAwno/ReservarResponse")]
        BuenosAires.Model.Respuesta Reservar(string nroSerieAnwo, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsProductoAwno/Reservar", ReplyAction="http://tempuri.org/IWsProductoAwno/ReservarResponse")]
        System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> ReservarAsync(string nroSerieAnwo, string usuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsProductoAwnoChannel : BuenosAires.BodegaBA.WsProductoAnwoReference.IWsProductoAwno, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsProductoAwnoClient : System.ServiceModel.ClientBase<BuenosAires.BodegaBA.WsProductoAnwoReference.IWsProductoAwno>, BuenosAires.BodegaBA.WsProductoAnwoReference.IWsProductoAwno {
        
        public WsProductoAwnoClient() {
        }
        
        public WsProductoAwnoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsProductoAwnoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsProductoAwnoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsProductoAwnoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BuenosAires.Model.Respuesta LeerTodos() {
            return base.Channel.LeerTodos();
        }
        
        public System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> LeerTodosAsync() {
            return base.Channel.LeerTodosAsync();
        }
        
        public BuenosAires.Model.Respuesta Reservar(string nroSerieAnwo, string usuario) {
            return base.Channel.Reservar(nroSerieAnwo, usuario);
        }
        
        public System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> ReservarAsync(string nroSerieAnwo, string usuario) {
            return base.Channel.ReservarAsync(nroSerieAnwo, usuario);
        }
    }
}
