//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuenosAires.BodegaBA.WsGuiaDespachoReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsGuiaDespachoReference.IWsGuiaDespacho")]
    public interface IWsGuiaDespacho {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsGuiaDespacho/ObtenerRespuesta", ReplyAction="http://tempuri.org/IWsGuiaDespacho/ObtenerRespuestaResponse")]
        BuenosAires.Model.Respuesta ObtenerRespuesta(BuenosAires.BusinessLayer.BcGuiaDespacho bc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsGuiaDespacho/ObtenerRespuesta", ReplyAction="http://tempuri.org/IWsGuiaDespacho/ObtenerRespuestaResponse")]
        System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> ObtenerRespuestaAsync(BuenosAires.BusinessLayer.BcGuiaDespacho bc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsGuiaDespacho/ValidarProducto", ReplyAction="http://tempuri.org/IWsGuiaDespacho/ValidarProductoResponse")]
        BuenosAires.Model.Respuesta ValidarProducto(BuenosAires.Model.GuiaDespacho guiaDespacho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsGuiaDespacho/ValidarProducto", ReplyAction="http://tempuri.org/IWsGuiaDespacho/ValidarProductoResponse")]
        System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> ValidarProductoAsync(BuenosAires.Model.GuiaDespacho guiaDespacho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsGuiaDespacho/Crear", ReplyAction="http://tempuri.org/IWsGuiaDespacho/CrearResponse")]
        BuenosAires.Model.Respuesta Crear(BuenosAires.Model.GuiaDespacho guiaDespacho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsGuiaDespacho/Crear", ReplyAction="http://tempuri.org/IWsGuiaDespacho/CrearResponse")]
        System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> CrearAsync(BuenosAires.Model.GuiaDespacho guiaDespacho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsGuiaDespacho/LeerTodos", ReplyAction="http://tempuri.org/IWsGuiaDespacho/LeerTodosResponse")]
        BuenosAires.Model.Respuesta LeerTodos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsGuiaDespacho/LeerTodos", ReplyAction="http://tempuri.org/IWsGuiaDespacho/LeerTodosResponse")]
        System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> LeerTodosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsGuiaDespacho/Leer", ReplyAction="http://tempuri.org/IWsGuiaDespacho/LeerResponse")]
        BuenosAires.Model.Respuesta Leer(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsGuiaDespacho/Leer", ReplyAction="http://tempuri.org/IWsGuiaDespacho/LeerResponse")]
        System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> LeerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsGuiaDespacho/Actualizar", ReplyAction="http://tempuri.org/IWsGuiaDespacho/ActualizarResponse")]
        BuenosAires.Model.Respuesta Actualizar(BuenosAires.Model.GuiaDespacho guiaDespacho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsGuiaDespacho/Actualizar", ReplyAction="http://tempuri.org/IWsGuiaDespacho/ActualizarResponse")]
        System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> ActualizarAsync(BuenosAires.Model.GuiaDespacho guiaDespacho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsGuiaDespacho/Eliminar", ReplyAction="http://tempuri.org/IWsGuiaDespacho/EliminarResponse")]
        BuenosAires.Model.Respuesta Eliminar(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsGuiaDespacho/Eliminar", ReplyAction="http://tempuri.org/IWsGuiaDespacho/EliminarResponse")]
        System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> EliminarAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsGuiaDespacho/CambiarEstado", ReplyAction="http://tempuri.org/IWsGuiaDespacho/CambiarEstadoResponse")]
        BuenosAires.Model.Respuesta CambiarEstado(int nrogd, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsGuiaDespacho/CambiarEstado", ReplyAction="http://tempuri.org/IWsGuiaDespacho/CambiarEstadoResponse")]
        System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> CambiarEstadoAsync(int nrogd, string estado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsGuiaDespachoChannel : BuenosAires.BodegaBA.WsGuiaDespachoReference.IWsGuiaDespacho, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsGuiaDespachoClient : System.ServiceModel.ClientBase<BuenosAires.BodegaBA.WsGuiaDespachoReference.IWsGuiaDespacho>, BuenosAires.BodegaBA.WsGuiaDespachoReference.IWsGuiaDespacho {
        
        public WsGuiaDespachoClient() {
        }
        
        public WsGuiaDespachoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsGuiaDespachoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsGuiaDespachoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsGuiaDespachoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BuenosAires.Model.Respuesta ObtenerRespuesta(BuenosAires.BusinessLayer.BcGuiaDespacho bc) {
            return base.Channel.ObtenerRespuesta(bc);
        }
        
        public System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> ObtenerRespuestaAsync(BuenosAires.BusinessLayer.BcGuiaDespacho bc) {
            return base.Channel.ObtenerRespuestaAsync(bc);
        }
        
        public BuenosAires.Model.Respuesta ValidarProducto(BuenosAires.Model.GuiaDespacho guiaDespacho) {
            return base.Channel.ValidarProducto(guiaDespacho);
        }
        
        public System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> ValidarProductoAsync(BuenosAires.Model.GuiaDespacho guiaDespacho) {
            return base.Channel.ValidarProductoAsync(guiaDespacho);
        }
        
        public BuenosAires.Model.Respuesta Crear(BuenosAires.Model.GuiaDespacho guiaDespacho) {
            return base.Channel.Crear(guiaDespacho);
        }
        
        public System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> CrearAsync(BuenosAires.Model.GuiaDespacho guiaDespacho) {
            return base.Channel.CrearAsync(guiaDespacho);
        }
        
        public BuenosAires.Model.Respuesta LeerTodos() {
            return base.Channel.LeerTodos();
        }
        
        public System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> LeerTodosAsync() {
            return base.Channel.LeerTodosAsync();
        }
        
        public BuenosAires.Model.Respuesta Leer(int id) {
            return base.Channel.Leer(id);
        }
        
        public System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> LeerAsync(int id) {
            return base.Channel.LeerAsync(id);
        }
        
        public BuenosAires.Model.Respuesta Actualizar(BuenosAires.Model.GuiaDespacho guiaDespacho) {
            return base.Channel.Actualizar(guiaDespacho);
        }
        
        public System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> ActualizarAsync(BuenosAires.Model.GuiaDespacho guiaDespacho) {
            return base.Channel.ActualizarAsync(guiaDespacho);
        }
        
        public BuenosAires.Model.Respuesta Eliminar(int id) {
            return base.Channel.Eliminar(id);
        }
        
        public System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> EliminarAsync(int id) {
            return base.Channel.EliminarAsync(id);
        }
        
        public BuenosAires.Model.Respuesta CambiarEstado(int nrogd, string estado) {
            return base.Channel.CambiarEstado(nrogd, estado);
        }
        
        public System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> CambiarEstadoAsync(int nrogd, string estado) {
            return base.Channel.CambiarEstadoAsync(nrogd, estado);
        }
    }
}
