//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuenosAires.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class django_admin_log
    {
        public int id { get; set; }
        public System.DateTimeOffset action_time { get; set; }
        public string object_id { get; set; }
        public string object_repr { get; set; }
        public short action_flag { get; set; }
        public string change_message { get; set; }
        public Nullable<int> content_type_id { get; set; }
        public int user_id { get; set; }
    
        public virtual auth_user auth_user { get; set; }
        public virtual django_content_type django_content_type { get; set; }
    }
}
