//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuenosAires.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class authtoken_token
    {
        public string key { get; set; }
        public System.DateTimeOffset created { get; set; }
        public int user_id { get; set; }
    
        public virtual auth_user auth_user { get; set; }
    }
}
